### PR TITLE
using attr<- instead of names<-

### PR DESCRIPTION
**Pull request by romainfrancois**
Because `tibble` has a method for `names<-`

### CODE REVIEW

**Comment by romainfrancois** [comment]
I have not tested installing `tibble` etc ... but I believe this would do the trick: 

``` r
library(tibble)
tbl <- tibble(f = 1:10)

`attr<-`(tbl, "names", NULL)
#> # A tibble: 10 x 1
#>    <int>
#>  1     1
#>  2     2
#>  3     3
#>  4     4
#>  5     5
#>  6     6
#>  7     7
#>  8     8
#>  9     9
#> 10    10
`names<-`(tbl, NULL)
#> Error: The `names` must not be `NULL`.
```

<sup>Created on 2018-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by krlmlr** [comment]
Running revdepchecks for tibble today, I'll test with r-devel to see the impact. My gut feeling is that this is just the tip of the iceberg, and that there are other places that are not prepared for a `names<-()` method to raise an error. If this is the case, we'll need another strategy (i.e., a warning or message instead of an error).

Should we discuss on r-devel first if `names<-()` methods are "allowed" to throw?

**Comment by romainfrancois** [comment]
Using `names<-` was introduced in this revision: https://github.com/wch/r-source/commit/9d9f8921f33bd68598be377ccfeffc4a8c669b3f

**Comment by lionel-** [comment]
cc @mmaechler

Hi Martin, this is about a fix to `duplicated.data.frame()` for a regression introduced in r75457. The problem is that this method now calls `names<-` to remove the names and this operation is not allowed on certain objects as it would break the invariants of the class. In particular, calling `names<-` with `NULL` on tibbles is an error, and there might be other cases.

We could override `duplicated()` for tibbles but ideally the data frame method would work for all subclasses of data frames, just like the `.default()` method would work for all types of vectors. There are two ways to go about this:

- Use `attr<-` which isn't generic. This is what Romain has implemented here and will work for all subclasses of data frames implemented around lists, like tibbles.

- First transform to a list with `as.list()` before unnaming. This is the most generic way since it will work with objects that implement the data frame interface but store the data in an internal field of the structure. In particular, transforming to a list first should work with S4 objects inheriting from `data.frame`.

Do any of these options make sense to you?

**Comment by mmaechler** [comment]
Hmm,  both versions will make `duplicated.data.frame()` slightly slower for the regular "base R" data frames.  The `attr<-`  solution seems extremely ugly to me compared to using `names<-`, and I tend to strictly refuse R code uglification.   Also, if as you demonstrate people can remove the names from a tibble anyway via `attr<-`   why do all the hoop jumping of forbid it via a `names<-` method?  

I find the underlying R codding issue too important to decide inside a github code comment alone, and so have asked for opinions within R-core.   Michael Lawrence (@lawremi) found a beatiful solution which I have now committed to R-devel (and plan to port to R-patched in due time).   So this time I hope we can all be happy ;-)

**Comment by romainfrancois** [comment]
I can confirm that the R-devel patch fixes the problem. https://travis-ci.org/tidyverse/dplyr/jobs/453218925#L1155

Thanks, closing this here.

**Comment by lionel-** [comment]
> Also, if as you demonstrate people can remove the names from a tibble anyway via attr<- why do all the hoop jumping of forbid it via a names<- method?

`attr()` is a low-level function for accessing internals of an object, it should normally only be used by developers or as a stopgap. `names<-` on the other hand is part of the vector interface and thus user-facing.

**Pull request closed without merging**
